love = {}
love.graphics = {}

function love.graphics.arc() end
function love.graphics.applyTransform() end
function love.graphics.captureScreenshot() end
function love.graphics.circle() end
function love.graphics.clear() end
function love.graphics.discard() end
function love.graphics.draw() end
function love.graphics.drawInstanced() end
function love.graphics.drawLayer() end
function love.graphics.ellipse() end
function love.graphics.flushBatch() end
function love.graphics.getBackgroundColor() end
function love.graphics.getBlendMode() end
function love.graphics.getCanvas() end
function love.graphics.getCanvasFormats() end
function love.graphics.getColor() end
function love.graphics.getColorMask() end
function love.graphics.getDefaultFilter() end
function love.graphics.getDepthMode() end
function love.graphics.getDimensions() end
function love.graphics.getFont() end
function love.graphics.getFrontFaceWinding() end
function love.graphics.getHeight() end
function love.graphics.getImageFormats() end
function love.graphics.getLineJoin() end
function love.graphics.getLineStyle() end
function love.graphics.getLineWidth() end
function love.graphics.getMeshCullMode() end
function love.graphics.getShader() end
function love.graphics.getStackDepth() end
function love.graphics.getStats() end
function love.graphics.getStencilTest() end
function love.graphics.getSupported() end
function love.graphics.getSystemLimits() end
function love.graphics.getPointSize() end
function love.graphics.getRendererInfo() end
function love.graphics.getScissor() end
function love.graphics.getTextureTypes() end
function love.graphics.getWidth() end
function love.graphics.intersectScissor() end
function love.graphics.inverseTransformPoint() end
function love.graphics.isGammaCorrect() end
function love.graphics.isWireframe() end
function love.graphics.line() end
function love.graphics.newCanvas() end
function love.graphics.newFont() end
function love.graphics.newMesh() end
function love.graphics.newImage() end
function love.graphics.newImageFont() end
function love.graphics.newParticleSystem() end
function love.graphics.newShader() end
function love.graphics.newText() end
function love.graphics.newQuad() end
function love.graphics.newSpriteBatch() end
function love.graphics.newVideo() end
function love.graphics.origin() end
function love.graphics.points() end
function love.graphics.polygon() end
function love.graphics.pop() end
function love.graphics.present() end
function love.graphics.print() end
function love.graphics.printf() end
function love.graphics.push() end
function love.graphics.rectangle() end
function love.graphics.replaceTransform() end
function love.graphics.reset() end
function love.graphics.rotate() end
function love.graphics.scale() end
function love.graphics.setBackgroundColor() end
function love.graphics.setBlendMode() end
function love.graphics.setCanvas() end
function love.graphics.setColor() end
function love.graphics.setColorMask() end
function love.graphics.setDefaultFilter() end
function love.graphics.setDepthMode() end
function love.graphics.setFont() end
function love.graphics.setFrontFaceWinding() end
function love.graphics.setLineJoin() end
function love.graphics.setLineStyle() end
function love.graphics.setLineWidth() end
function love.graphics.setMeshCullMode() end
function love.graphics.setNewFont() end
function love.graphics.setShader() end
function love.graphics.setPointSize() end
function love.graphics.setScissor() end
function love.graphics.setStencilTest() end
function love.graphics.setWireframe() end
function love.graphics.shear() end
function love.graphics.stencil() end
function love.graphics.transformPoint() end
function love.graphics.translate() end
function love.graphics.validateShader() end
